disabled_rules:
  - force_cast
  - force_try
  - missing_docs
opt_in_rules:
  - empty_count
included:
  - Classes
excluded:
  - Pods

function_parameter_count: 7
line_length: 210
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
function_body_length:
    warning: 50
    error: 70
cyclomatic_complexity:
    warning: 15
    error: 25
large_tuple:
    warning: 4
    error: 6
identifier_name:
  min_length:
    warning: 1
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" #(xcode, json, csv, checkstyle, junit)
