//
//  HeaderSectionTitleVM.swift
//  Chili Labs
//
//  Generated by Chigevara on 13/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import Foundation
import MagazineLayout

struct HeaderSectionTitleVM: MagazineSupplementaryDataType {

    let heightMode: MagazineLayoutHeaderHeightMode = .static(height: 64)

    let title: String
    let subtitle: String

    init(title: String, subtitle: String) {
        self.title = title
        self.subtitle = subtitle
    }

    var diffHash: Int {
        return title.hashValue
    }

    func configurator() -> SupplementaryCellConfigurator {
        return HeaderSectionTitleConfigurator(item: self)
    }
}

