//
//  HeaderSectionTitle.swift
//  Chili Labs
//
//  Generated by Chigevara on 13/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import UIKit
import RxSwift
import RxCocoa

typealias HeaderSectionTitleConfigurator = MagazineSupplementaryCellConfigurator<HeaderSectionTitleVM, HeaderSectionTitle>

final class HeaderSectionTitle: UICollectionReusableView, ConfigurableCell {

    private let titleLabel: UILabel = {
        let l = UILabel(frame: .zero)
        l.bonMotStyle = Typography.Headline2
        return l
    }()

    private let subtitleLabel: UILabel = {
        let l = UILabel(frame: .zero)
        l.bonMotStyle = Typography.Caption
        l.textColor = UIColor.captionText
        return l
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        self.addSubview(titleLabel)
        titleLabel.snp.makeConstraints {
            $0.leading.trailing.equalToSuperview()
            $0.top.equalToSuperview().offset(8)
        }

        self.addSubview(subtitleLabel)
        subtitleLabel.snp.makeConstraints {
            $0.leading.trailing.equalToSuperview()
            $0.top.equalTo(self.titleLabel.snp.bottom).offset(4)
        }
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func configure(item: HeaderSectionTitleVM) {
        titleLabel.styledText = item.title
        subtitleLabel.styledText = item.subtitle
    }
}
