//
//  RowHeadline1VM.swift
//  Chili Labs
//
//  Generated by Chigevara on 12/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import Foundation
import MagazineLayout
import RxFlow
import RxSwift
import RxCocoa

struct RowHeadline1VM: MagazineCellDataType {

    var sizeMode: MagazineLayoutItemSizeMode {
        return MagazineLayoutItemSizeMode(widthMode: .fullWidth(respectsHorizontalInsets: true),
                                          heightMode: .dynamic)
    }

    let title: String

    init(title: String) {
        self.title = title
    }

    var diffHash: Int {
        return title.hashValue
    }

    func configurator() -> CellConfigurator {
        return RowHeadline1Configurator(item: self)
    }

    func didSelect() {
        //
    }
}

