//
//  RowCaption.swift
//  Chili Labs
//
//  Generated by Chigevara on 13/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import UIKit
import MagazineLayout

typealias RowCaptionConfigurator = MagazineCellConfigurator<RowCaptionVM, RowCaption>
final class RowCaption: MagazineLayoutCollectionViewCell, ConfigurableCell {

    private let textLabel: UILabel = {
        let label = UILabel(frame: .zero)
        label.bonMotStyle = Typography.Caption
        label.numberOfLines = 0
        label.textColor = .captionText
        return label
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        self.contentView.addSubview(textLabel)
        textLabel.snp.makeConstraints {
            $0.leading.trailing.equalToSuperview()
            $0.top.bottom.equalToSuperview()
        }
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func configure(item: RowCaptionVM) {
        self.textLabel.styledText = item.title
    }
}
