//
//  CardPhotoThumbnailVM.swift
//  Chili Labs
//
//  Generated by Chigevara on 14/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import Foundation
import MagazineLayout
import RxFlow
import RxSwift
import RxCocoa

struct CardPhotoThumbnailVM: MagazineCellDataType {

    var sizeMode: MagazineLayoutItemSizeMode {
        return MagazineLayoutItemSizeMode(widthMode: .thirdWidth,
                                          heightMode: .static(height: 120))
    }

    let url: String

    init(url: String) {
        self.url = url
    }

    var diffHash: Int {
        return url.hashValue
    }

    func configurator() -> CellConfigurator {
        return CardPhotoThumbnailConfigurator(item: self)
    }

    func didSelect() {
        //
    }
}

