//
//  CardPhotoThumbnail.swift
//  Chili Labs
//
//  Generated by Chigevara on 14/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import UIKit
import MagazineLayout

typealias CardPhotoThumbnailConfigurator = MagazineCellConfigurator<CardPhotoThumbnailVM, CardPhotoThumbnail>
final class CardPhotoThumbnail: UICollectionViewCell, ConfigurableCell {

    private let imageView: UIImageView = {
        let v = UIImageView()
        v.contentMode = .scaleAspectFill
        v.layer.cornerRadius = 6
        v.clipsToBounds = true
        v.backgroundColor = .placeholder
        return v
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        self.contentView.addSubview(imageView)
        imageView.snp.makeConstraints {
            $0.edges.equalToSuperview()
        }
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func configure(item: CardPhotoThumbnailVM) {
        self.imageView.kf.setImage(with: URL(string: item.url),
                                   options: [.transition(.fade(0.3))])
    }
}
