//
//  RowFlightInfoVM.swift
//  Chili Labs
//
//  Generated by Chigevara on 13/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import Foundation
import MagazineLayout
import RxFlow
import RxSwift
import RxCocoa

struct FlightInfo: Hashable {
    let departureTime: String
    let departureAirport: String

    let arrivalTime: String
    let arrivalAirport: String
}

struct RowFlightInfoVM: MagazineCellDataType {

    var sizeMode: MagazineLayoutItemSizeMode {
        return MagazineLayoutItemSizeMode(widthMode: .fullWidth(respectsHorizontalInsets: true),
                                          heightMode: .static(height: 60))
    }

    let flightInfo: FlightInfo

    init(info: FlightInfo) {
        self.flightInfo = info
    }

    var diffHash: Int {
        return flightInfo.hashValue
    }

    func configurator() -> CellConfigurator {
        return RowFlightInfoConfigurator(item: self)
    }

    func didSelect() {
        //
    }
}

