//
//  RowFlightInfo.swift
//  Chili Labs
//
//  Generated by Chigevara on 13/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import UIKit
import MagazineLayout

typealias RowFlightInfoConfigurator = MagazineCellConfigurator<RowFlightInfoVM, RowFlightInfo>
final class RowFlightInfo: MagazineLayoutCollectionViewCell, ConfigurableCell {

    static var nib: UINib? { return UINib(nibName: self.reuseIdentifier, bundle: nil) }

    @IBOutlet weak var departureTimeLabel: UILabel!
    @IBOutlet weak var arrivalTimeLabel: UILabel!
    @IBOutlet weak var departureDestinationLabel: UILabel!
    @IBOutlet weak var arrivalDestinationLabel: UILabel!

    func configure(item: RowFlightInfoVM) {
        self.departureTimeLabel.styledText = item.flightInfo.departureTime
        self.departureDestinationLabel.styledText = item.flightInfo.departureAirport

        self.arrivalTimeLabel.styledText = item.flightInfo.arrivalTime
        self.arrivalDestinationLabel.styledText = item.flightInfo.arrivalAirport
    }
}
