//
//  RowText.swift
//  Chili Labs
//
//  Generated by Chigevara on 14/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import UIKit
import MagazineLayout

typealias RowTextConfigurator = MagazineCellConfigurator<RowTextVM, RowText>
final class RowText: MagazineLayoutCollectionViewCell, ConfigurableCell {

    private let textLabel: UILabel = {
        let label = UILabel(frame: .zero)
        label.bonMotStyle = Typography.Text
        label.numberOfLines = 0
        label.textColor = .captionText
        return label
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        self.contentView.addSubview(textLabel)
        textLabel.snp.makeConstraints {
            $0.leading.trailing.equalToSuperview()
            $0.top.bottom.equalToSuperview()
        }
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func configure(item: RowTextVM) {
        textLabel.styledText = item.text
    }
}
