//
//  HeaderHeadline2.swift
//  Chili Labs
//
//  Generated by Chigevara on 14/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import UIKit
import RxSwift
import RxCocoa

typealias HeaderHeadline2Configurator = MagazineSupplementaryCellConfigurator<HeaderHeadline2VM, HeaderHeadline2>

final class HeaderHeadline2: UICollectionReusableView, ConfigurableCell {

    private let textLabel: UILabel = {
        let label = UILabel(frame: .zero)
        label.bonMotStyle = Typography.Headline2
        label.numberOfLines = 0
        label.textColor = .mainText
        return label
    }()

    override init(frame: CGRect) {
        super.init(frame: frame)

        self.addSubview(textLabel)
        textLabel.snp.makeConstraints {
            $0.leading.trailing.equalToSuperview()
            $0.top.bottom.equalToSuperview().inset(8)
        }
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    func configure(item: HeaderHeadline2VM) {
        textLabel.styledText = item.title
    }
}
