//
//  HeaderHeadline2VM.swift
//  Chili Labs
//
//  Generated by Chigevara on 14/05/2020.
//  Copyright © 2020 Chili Labs. All rights reserved.
//

import Foundation
import MagazineLayout
import RxFlow
import RxSwift
import RxCocoa

struct HeaderHeadline2VM: MagazineSupplementaryDataType {

    let heightMode: MagazineLayoutHeaderHeightMode = .dynamic

    let title: String

    init(title: String) {
        self.title = title
    }

    var diffHash: Int {
        return title.hashValue
    }

    func configurator() -> SupplementaryCellConfigurator {
        return HeaderHeadline2Configurator(item: self)
    }
}

